Update publish_conda.yml

diff --git a/.github/workflows/publish_conda.yml b/.github/workflows/publish_conda.yml
--- a/.github/workflows/publish_conda.yml
+++ b/.github/workflows/publish_conda.yml
@@ -58,11 +58,26 @@ jobs:
           conda install conda-forge::conda-build conda-forge::anaconda-client
 
       - name: Build fremor Conda Package
+        env:
+          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
         run: |
-          echo "conda building fremor package"
-          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
+          echo "quick sanity check, is the token available as a secret? is the env var set?"
+          if [ -z "${{ secrets.ANACONDA_TOKEN }}" ]; then
+             echo "ERROR: ANACONDA_TOKEN is empty or not accessible"
+             exit 1
+          else
+             echo "ANACONDA_TOKEN is set (length: ${#ANACONDA_API_TOKEN})"
+          fi
+
+          echo "printing conda config... again... just in case..."
+          conda config --show
+
+          echo "conda build version is"
           conda build --version
+
+          echo "building conda package for publishing"
           conda build --debug .
+          echo "extra info from additional force-upload step:"
           anaconda --verbose upload --force /home/runner/miniconda3/envs/test/conda-bld/noarch/fremor-develop-py_0.conda
 
       # -----------------------------------------------------------------
@@ -82,7 +97,7 @@ jobs:
 
       - name: Create clean environment and install fremor from noaa-gfdl
         run: |
-          conda create -y -n fremor-verify python=${{ matrix.python-version }}
+          conda create -y -n fremor-verify
           conda activate fremor-verify
           conda install -y -c noaa-gfdl -c conda-forge fremor
           conda install -y conda-forge::pytest
